name: salatime
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dropdown_formfield: ^0.1.3
  http: ^0.13.3
  json_annotation: ^4.0.1
  select_form_field: ^2.0.0
  quiver: ^3.0.1
  timer_count_down: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  json_serializable: ^4.1.1

flutter:
  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
    - family: Mada
      fonts:
        - asset: fonts/Mada-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
  uses-material-design: true
